### ISSUE TITLE
Each step removes all dead agents from grid

### ISSUE THREAD

**Issue by zmuda** [maciek123/pyage#3]
When making step by agent, removing all dead agents is invoked [(line)](https://github.com/maciek123/pyage/blob/master/pyage/core/locator.py#L73).

I'm not sure if traversing the whole grid [(here)](https://github.com/maciek123/pyage/blob/master/pyage/core/locator.py#L93-96) is needed, maybe checking only possible neighborhood would suffice. That would reduce step complexity a great deal. Change should be simple as possible neighborhood is already calculated in scope [(here)](https://github.com/maciek123/pyage/blob/master/pyage/core/locator.py#L75). 
Only question is if such change breaks validity of an algorithm.

**Comment by maciek123** [comment]
Good spot! I've fixed it in [commit 1bd94fcecd2eddf97b24cef4dfa5a279bb488997](https://github.com/maciek123/pyage/commit/1bd94fcecd2eddf97b24cef4dfa5a279bb488997)
